### ISSUE TITLE
BF-LVDT preparation

### ISSUE THREAD

**Issue by gw-vis** [gw-vis/ITMX_installation#1]
### TODO & checklist
- [x] tune phase and gain on the LVDT card
- [x] calibration
- [x] noise measurement
- [x] the nose level at 10 Hz is about: 5e-9 to 1e-9 ?

**References**
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=5656

**Comment by YoshinoriFujii** [comment]
result (ongoing):
[ITMX_BF_LVDT_calib_20180428.pdf](https://github.com/gw-vis/ITMX_installation/files/1958570/ITMX_BF_LVDT_calib_20180428.pdf)

**Comment by YoshinoriFujii** [comment]
For ITMX

| number#  | calibration factor [um/cnt] | linear range [cnt] | for which? | noise level at 10 Hz |
|:---:|:---:|:---:|:---:|:---:|
| V1 | 0.3538 | -17010 to 22340 | BF-LVDT-V1 | 8.77e-09 m/rtHz |
| V2 | 0.3664  | -18991 to 21668 | BF-LVDT-V2 | 5.65e-09 m/rtHz |
| V3 | 0.385  |  | BF-LVDT-V3 |  |
| H1 | 0.371  |  | BF-LVDT-H1 |  |
| H2 | 0.382 |  | BF-LVDT-H2 |  |
| H3 | 0.387 |  | BF-LVDT-H3 |  |
|  |  |  |  |  |
| proto |  |  |  | 1.19e-08 m/rtHz |

[klog5002](http://klog.icrr.u-tokyo.ac.jp/osl/?r=5002 "klog5002")
